#!/bin/bash
# Quick Deploy Script for GitHub + Vercel

echo "🚀 Fitness 90-Day PWA Tracker - GitHub Deployment"
echo "=================================================="
echo ""
echo "📋 Pre-requisites:"
echo "   ✅ Code is committed and ready"
echo "   ✅ All services running"
echo "   ✅ Application tested at http://localhost:3000"
echo ""
echo "🎯 Next Steps:"
echo ""
echo "1️⃣  CREATE GITHUB REPOSITORY"
echo "   Go to: https://github.com/new"
echo "   Name: fitness-90-day-tracker"
echo "   Visibility: Public or Private"
echo "   DO NOT initialize with README"
echo ""
echo "2️⃣  COPY YOUR REPOSITORY URL"
echo "   Example: https://github.com/YOUR_USERNAME/fitness-90-day-tracker.git"
echo ""
echo "3️⃣  RUN THESE COMMANDS:"
echo ""
echo "   cd /app"
echo "   git remote add origin YOUR_GITHUB_URL_HERE"
echo "   git push -u origin main"
echo ""
echo "4️⃣  DEPLOY TO VERCEL"
echo "   Go to: https://vercel.com/new"
echo "   Click: Continue with GitHub"
echo "   Import: fitness-90-day-tracker"
echo "   Configure:"
echo "     - Root Directory: frontend"
echo "     - Keep all other defaults"
echo "   Click: Deploy"
echo ""
echo "5️⃣  ACCESS YOUR LIVE APP"
echo "   Vercel will provide URL:"
echo "   https://fitness-90-day-tracker.vercel.app"
echo ""
echo "=================================================="
echo "📚 Full Guide: /app/GITHUB_VERCEL_DEPLOY.md"
echo "=================================================="
